/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Computer.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Computer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Comp_Mouse.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.System_unit.geometry} material={materials.initialShadingGroup} />
    </group>
  )
}

useGLTF.preload('/Computer-transformed.glb')
